### ISSUE TITLE
New version not showing bosses + loot

### ISSUE THREAD

**Issue by Fluffykitten1234** [Otari98/Atlas#1]
![Old version](https://github.com/user-attachments/assets/68dd489c-f401-4b5c-ba68-55b390cc8078)
![New version](https://github.com/user-attachments/assets/98f49a80-85ee-42ad-8ac2-3a00243946fb)
When updating the addon from 1.13.2 to 1.13.3, boss names and loot are no longer visible.
Any idea how to fix this? 
Atlasloot + Atlasquest we're also updated to their latest version alongside with this and have no issue's.

**Comment by Otari98** [comment]
Works with this version https://github.com/Otari98/AtlasLoot

**Comment by Fluffykitten1234** [comment]
Thank you, its working now
